apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "event-system.fullname" . }}-gateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "event-system.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.istio.gateway.ingressGatewaySelector | nindent 4 }}
    matchLabels:
      {{- include "event-system.selectorLabels" . | nindent 6 }}
  servers:
    - port:
        number: {{ .Values.istio.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        {{- toYaml .Values.istio.gateway.hosts | nindent 8 }}
