apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-system.fullname" . }}-scheduler
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "event-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
    - name: http
      port: {{ .Values.scheduler.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "event-system.selectorLabels" . | nindent 4 }}
